apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
    service: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-controller
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
     app: mongo
     version: v1
  template:
    metadata:
      labels:
        app: mongo
        version: v1
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage-mern
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage-mern
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4
